// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close(arg1) {
  return window['go']['ptyapi']['Service']['Close'](arg1);
}

export function Open(arg1, arg2) {
  return window['go']['ptyapi']['Service']['Open'](arg1, arg2);
}

export function Resize(arg1, arg2, arg3) {
  return window['go']['ptyapi']['Service']['Resize'](arg1, arg2, arg3);
}

export function Sessions() {
  return window['go']['ptyapi']['Service']['Sessions']();
}

export function Shutdown() {
  return window['go']['ptyapi']['Service']['Shutdown']();
}

export function Startup(arg1) {
  return window['go']['ptyapi']['Service']['Startup'](arg1);
}

export function Write(arg1, arg2) {
  return window['go']['ptyapi']['Service']['Write'](arg1, arg2);
}
