// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ptyapi} from '../models';
import {context} from '../models';

export function Close(arg1:string):Promise<boolean>;

export function Open(arg1:string,arg2:ptyapi.OpenRequest):Promise<ptyapi.SessionInfo>;

export function Resize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function Sessions():Promise<Array<ptyapi.SessionInfo>>;

export function Shutdown():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function Write(arg1:string,arg2:string):Promise<void>;
