/**
 * `git stash list -z --format=…`.
 *
 * The stash is a log walk over `refs/stash`, so it takes the same format atoms
 * as `git log` and produces the same NUL-terminated field layout — see
 * `log.ts` for why the field count is the only record boundary.
 *
 * Two things here are not obvious:
 *
 * **Whether untracked files were stashed is in the parent count, not the
 * message.** A stash commit has two parents (HEAD and the index tree), or
 * *three* when `-u` was used — the third is the untracked tree. Verified
 * against git 2.47. Matching on the message text would be guesswork; counting
 * parents is exact.
 *
 * **The reflog subject has two shapes.** `git stash` with no message produces
 * `WIP on main: ffd1b3e first commit`; `git stash -m "…"` produces
 * `On main: …`. Both encode the branch, and the UI wants the branch and the
 * message separately, so both are unpicked here.
 */

/** Placeholders in `STASH_FORMAT`, in order. */
const FIELDS = [
  'gd', // reflog selector, e.g. stash@{0}
  'H', // stash commit id
  'P', // parents — two normally, three when untracked files were included
  'gs', // reflog subject: "On <branch>: …" or "WIP on <branch>: …"
  'ct', // committer date, unix seconds
] as const;

export const STASH_FORMAT = FIELDS.map((field) => `%${field}`).join('%x00');

/** `-z` is required: the parser relies on NUL-terminated fields. */
export const STASH_LIST_ARGS: readonly string[] = [
  'stash',
  'list',
  '-z',
  `--format=${STASH_FORMAT}`,
];

export interface Stash {
  /** Position in the stack; 0 is the most recent. */
  readonly index: number;
  /** The ref to pass back to git, e.g. `stash@{0}`. */
  readonly selector: string;
  readonly oid: string;
  /** Branch the stash was created on, or null if the subject was unrecognisable. */
  readonly branch: string | null;
  /** The user's message, or git's auto-generated description. */
  readonly message: string;
  /** True when the message was generated by git rather than written by the user. */
  readonly autoNamed: boolean;
  /** `git stash -u` — the working tree's untracked files are in here too. */
  readonly includesUntracked: boolean;
  /** Unix seconds. */
  readonly date: number;
}

/** See `StatusParseError` — a format mismatch is our bug, not the user's. */
export class StashParseError extends Error {
  constructor(
    message: string,
    readonly record: string,
  ) {
    super(`${message}: ${JSON.stringify(record)}`);
    this.name = 'StashParseError';
  }
}

const SELECTOR = /^stash@\{(\d+)\}$/;

/**
 * Split `On main: my message` / `WIP on main: abc1234 subject` into its parts.
 *
 * A branch name may contain a colon-space sequence in principle, but the
 * prefix is fixed, so only the *first* separator after the prefix matters.
 */
function parseSubject(subject: string): {
  branch: string | null;
  message: string;
  autoNamed: boolean;
} {
  const auto = /^WIP on ([^:]+): (.*)$/s.exec(subject);
  if (auto !== null) {
    return { branch: auto[1] ?? null, message: auto[2] ?? '', autoNamed: true };
  }

  const named = /^On ([^:]+): (.*)$/s.exec(subject);
  if (named !== null) {
    return { branch: named[1] ?? null, message: named[2] ?? '', autoNamed: false };
  }

  // Anything else is still a stash; show the subject verbatim rather than
  // dropping it because it did not match a pattern.
  return { branch: null, message: subject, autoNamed: false };
}

export function parseStashList(stdout: string): Stash[] {
  const fields = stdout.split('\0');
  // Every field is NUL-terminated, so a trailing empty piece is expected.
  if (fields[fields.length - 1] === '') fields.pop();
  if (fields.length === 0) return [];

  if (fields.length % FIELDS.length !== 0) {
    throw new StashParseError(
      `expected a multiple of ${FIELDS.length} fields, got ${fields.length}`,
      fields.slice(0, FIELDS.length).join('\0'),
    );
  }

  const stashes: Stash[] = [];
  for (let i = 0; i < fields.length; i += FIELDS.length) {
    const [selector = '', oid = '', parents = '', subject = '', date = ''] = fields.slice(
      i,
      i + FIELDS.length,
    );

    const match = SELECTOR.exec(selector);
    if (match === null) {
      throw new StashParseError('expected a stash@{n} selector', selector);
    }

    const { branch, message, autoNamed } = parseSubject(subject);
    const parentCount = parents === '' ? 0 : parents.split(' ').length;

    stashes.push({
      index: Number.parseInt(match[1] ?? '0', 10),
      selector,
      oid,
      branch,
      message,
      autoNamed,
      // Two parents is the ordinary case; the third is the untracked tree.
      includesUntracked: parentCount >= 3,
      date: Number.parseInt(date, 10) || 0,
    });
  }

  return stashes;
}
