/**
 * Real `git status --porcelain=v2 -z` output, captured from git 2.47.1.
 *
 * Generated by running the commands against purpose-built repositories, not
 * written by hand: a fixture that merely looks like git's output would let the
 * parser pass while the app corrupts filenames. NULs appear as \x00 rather than
 * \0, which JavaScript reads as an octal escape when the next byte is a digit.
 */

/**
 * Everything at once: a staged-then-modified add, two renames (git resolved the
 * copy into a rename from the deleted file), an unstaged modify, a dirty
 * submodule, a merge conflict, untracked paths containing a newline, tab, quote
 * and backslash, and an ignored file.
 */
export const STATUS_EVERYTHING =
  '# branch.oid a57cf68f7bbec713a1d008ea6c68689804505599\x00# branch.head main\x00# branch.upstream origin/main\x00# branch.ab +2 -0\x001 AM N... 000000 100644 100644 0000000000000000000000000000000000000000 19d9cc8584ac2c7dcf57d2680375e80f099dc481 added.txt\x002 R. N... 100644 100644 100644 0c2aa38e0600e0d2df09c2f84664d8a14f899879 0c2aa38e0600e0d2df09c2f84664d8a14f899879 R100 copydst.txt\x00deleteme.txt\x001 .M N... 100644 100644 100644 0c2aa38e0600e0d2df09c2f84664d8a14f899879 0c2aa38e0600e0d2df09c2f84664d8a14f899879 modifyme.txt\x002 R. N... 100644 100644 100644 0c2aa38e0600e0d2df09c2f84664d8a14f899879 0c2aa38e0600e0d2df09c2f84664d8a14f899879 R100 renamed.txt\x00renameme.txt\x001 .M S.M. 160000 160000 160000 970a1fe71b2d27ff0b96ee4877b4e2b1b052c703 970a1fe71b2d27ff0b96ee4877b4e2b1b052c703 sub\x00u AA N... 000000 100644 100644 100644 0000000000000000000000000000000000000000 ba2906d0666cf726c7eaadd2cd3db615dedfdf3a c7747099cf9e073babc68f52cdfb4d280ba5689f conflict.txt\x00? .gitignore\x00? newline\nin\tname.txt\x00? quote"and\\backslash.txt\x00? space in name.txt\x00! ignored.log\x00';

/**
 * Paths that defeat whitespace-splitting parsers: a leading space (which puts two
 * consecutive spaces in the record), a trailing space, and doubled inner spaces —
 * plus a symlink (mode 120000) and an exec-bit change (100644 to 100755).
 */
export const STATUS_AWKWARD_PATHS =
  '# branch.oid 894c8fe2e7df875aaffbfdee860208d61a808467\x00# branch.head main\x001 M. N... 100644 100644 100644 587be6b4c3f93f93c489c0111bba5596147a26cb b77b4eb1d946f923f61785536da9ca5af6909f06  leading space.txt\x001 M. N... 100644 100644 100644 587be6b4c3f93f93c489c0111bba5596147a26cb b77b4eb1d946f923f61785536da9ca5af6909f06 a b  c.txt\x001 A. N... 000000 120000 120000 0000000000000000000000000000000000000000 1defec451987c9144f4671725e20382b3dafcfb6 link.txt\x001 M. N... 100644 100755 100755 587be6b4c3f93f93c489c0111bba5596147a26cb 587be6b4c3f93f93c489c0111bba5596147a26cb trailing space .txt\x00';

/** A fresh `git init`: HEAD points at a branch that has no commits yet. */
export const STATUS_UNBORN = '# branch.oid (initial)\x00# branch.head main\x00';

/** Detached HEAD, which git reports as a branch name of `(detached)`. */
export const STATUS_DETACHED =
  '# branch.oid a85ff03d07c37ee4189d059cca27e12ba254a7c4\x00# branch.head (detached)\x00';

/** Nothing to report: headers only, no entries, and no upstream configured. */
export const STATUS_CLEAN =
  '# branch.oid 160b4ea650f406a260024365c24a5776b45b5cdc\x00# branch.head main\x00';
