// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dialogs} from '../models';
import {context} from '../models';

export function SaveFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SelectDirectory(arg1:string,arg2:string):Promise<string>;

export function SelectFile(arg1:string,arg2:string):Promise<string>;

export function ShowMessage(arg1:dialogs.MessageOptions):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
