// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['gitexec']['Service']['Cancel'](arg1);
}

export function Info() {
  return window['go']['gitexec']['Service']['Info']();
}

export function Run(arg1) {
  return window['go']['gitexec']['Service']['Run'](arg1);
}

export function RunBase64(arg1) {
  return window['go']['gitexec']['Service']['RunBase64'](arg1);
}

export function RunStream(arg1, arg2) {
  return window['go']['gitexec']['Service']['RunStream'](arg1, arg2);
}

export function SetGitPath(arg1) {
  return window['go']['gitexec']['Service']['SetGitPath'](arg1);
}

export function Startup(arg1) {
  return window['go']['gitexec']['Service']['Startup'](arg1);
}
