// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gitexec} from '../models';
import {context} from '../models';

export function Cancel(arg1:string):Promise<boolean>;

export function Info():Promise<gitexec.GitInfo>;

export function Run(arg1:gitexec.RunRequest):Promise<gitexec.RunResult>;

export function RunBase64(arg1:gitexec.RunRequest):Promise<gitexec.RunResult>;

export function RunStream(arg1:string,arg2:gitexec.StreamRequest):Promise<gitexec.StreamResult>;

export function SetGitPath(arg1:string):Promise<gitexec.GitInfo>;

export function Startup(arg1:context.Context):Promise<void>;
