#!/usr/bin/env bash
#
# vendor-fonts.sh — download JetBrains Mono + Space Grotesk from Google Fonts
# into frontend/src/assets/fonts/ so moonGit never depends on a CDN at runtime.
# The mockup loaded these from fonts.googleapis.com; a packaged Wails app serves
# from an embedded FS and may be offline (PLAN.md §1.3).
#
# Both families are variable fonts, so Google serves ONE file per unicode subset
# covering the whole weight range — this script de-duplicates and emits a single
# @font-face per (family, subset) with a `font-weight: 400 700` range.
#
# Usage: ./scripts/vendor-fonts.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FONT_DIR="$SCRIPT_DIR/../frontend/src/assets/fonts"
mkdir -p "$FONT_DIR"
cd "$FONT_DIR"

UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"
URL="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600;700&family=Space+Grotesk:wght@400;500;600;700&display=swap"

echo "fetching font CSS…"
curl -sfL -A "$UA" "$URL" -o .gf.css

python3 - <<'PY'
import re, urllib.request, pathlib, hashlib

css = pathlib.Path(".gf.css").read_text()
KEEP = {"latin", "latin-ext"}   # drop cyrillic/greek/vietnamese — not needed
SLUG = {"JetBrains Mono": "jetbrains-mono", "Space Grotesk": "space-grotesk"}

blocks = re.findall(r"/\* (\S+) \*/\s*(@font-face \{.*?\})", css, re.S)

# (family, subset) -> {url, range}. Weights collapse because these are variable
# fonts: every requested weight resolves to the same file.
faces = {}
for subset, block in blocks:
    if subset not in KEEP:
        continue
    fam = re.search(r"font-family: '([^']+)'", block).group(1)
    key = (fam, subset)
    if key in faces:
        continue
    faces[key] = {
        "url": re.search(r"url\((https://[^)]+)\)", block).group(1),
        "range": re.search(r"unicode-range: ([^;]+);", block).group(1),
    }

# Remove previously vendored files so a re-run doesn't leave orphans behind.
for old in pathlib.Path(".").glob("*.woff2"):
    old.unlink()

rules = []
for (fam, subset), face in sorted(faces.items()):
    name = f"{SLUG[fam]}-{subset}.woff2"
    urllib.request.urlretrieve(face["url"], name)
    size = pathlib.Path(name).stat().st_size
    print(f"  {name}  {size/1024:.1f} KB")
    rules.append(f"""@font-face {{
  font-family: '{fam}';
  font-style: normal;
  font-weight: 400 700; /* variable */
  font-display: swap;
  src: url('./{name}') format('woff2');
  unicode-range: {face['range']};
}}""")

pathlib.Path("fonts.css").write_text(
    "/* Vendored from Google Fonts — moonGit ships offline, no CDN at runtime.\n"
    "   Generated by scripts/vendor-fonts.sh — do not edit by hand.\n"
    "   Variable fonts: one file per subset covers weights 400–700. */\n\n"
    + "\n\n".join(rules) + "\n"
)
total = sum(p.stat().st_size for p in pathlib.Path(".").glob("*.woff2"))
print(f"{len(rules)} @font-face rules, {total/1024:.1f} KB total")
PY

rm -f .gf.css
echo "done → $FONT_DIR/fonts.css"
