// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appmenu} from '../models';
import {context} from '../models';

export function Set(arg1:Array<appmenu.Menu>):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
