// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Set(arg1) {
  return window['go']['appmenu']['Service']['Set'](arg1);
}

export function Startup(arg1) {
  return window['go']['appmenu']['Service']['Startup'](arg1);
}
