// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fsapi} from '../models';

export function DeletePath(arg1:string):Promise<void>;

export function Exists(arg1:string):Promise<boolean>;

export function HomeDir():Promise<string>;

export function ListDir(arg1:string):Promise<Array<fsapi.FileInfo>>;

export function ReadFile(arg1:string):Promise<fsapi.FileContent>;

export function ReadFileBase64(arg1:string):Promise<fsapi.FileContent>;

export function Stat(arg1:string):Promise<fsapi.FileInfo>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
