// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Exists(arg1) {
  return window['go']['fsapi']['Service']['Exists'](arg1);
}

export function HomeDir() {
  return window['go']['fsapi']['Service']['HomeDir']();
}

export function ListDir(arg1) {
  return window['go']['fsapi']['Service']['ListDir'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['fsapi']['Service']['ReadFile'](arg1);
}

export function ReadFileBase64(arg1) {
  return window['go']['fsapi']['Service']['ReadFileBase64'](arg1);
}

export function Stat(arg1) {
  return window['go']['fsapi']['Service']['Stat'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['fsapi']['Service']['WriteFile'](arg1, arg2);
}
