// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Available() {
  return window['go']['creds']['Service']['Available']();
}

export function Delete(arg1) {
  return window['go']['creds']['Service']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['creds']['Service']['Get'](arg1);
}

export function Set(arg1, arg2) {
  return window['go']['creds']['Service']['Set'](arg1, arg2);
}
