// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {creds} from '../models';

export function Available():Promise<boolean>;

export function Delete(arg1:string):Promise<void>;

export function Get(arg1:string):Promise<creds.Secret>;

export function Set(arg1:string,arg2:string):Promise<void>;
