// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenExternal(arg1) {
  return window['go']['shellapi']['Service']['OpenExternal'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['shellapi']['Service']['OpenPath'](arg1);
}

export function OpenTerminal(arg1) {
  return window['go']['shellapi']['Service']['OpenTerminal'](arg1);
}

export function RevealInFinder(arg1) {
  return window['go']['shellapi']['Service']['RevealInFinder'](arg1);
}

export function Startup(arg1) {
  return window['go']['shellapi']['Service']['Startup'](arg1);
}
