// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {watcher} from '../models';

export function Startup(arg1:context.Context):Promise<void>;

export function Unwatch(arg1:string):Promise<boolean>;

export function Watch(arg1:string,arg2:Array<string>):Promise<watcher.WatchInfo>;

export function Watching():Promise<Array<watcher.WatchInfo>>;
