// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Startup(arg1) {
  return window['go']['watcher']['Service']['Startup'](arg1);
}

export function Unwatch(arg1) {
  return window['go']['watcher']['Service']['Unwatch'](arg1);
}

export function Watch(arg1) {
  return window['go']['watcher']['Service']['Watch'](arg1);
}

export function Watching() {
  return window['go']['watcher']['Service']['Watching']();
}
