// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {context} from '../models';

export function Close():Promise<void>;

export function Exec(arg1:string,arg2:Array<any>):Promise<store.ExecResult>;

export function ExecBatch(arg1:Array<store.Statement>):Promise<store.ExecResult>;

export function Info():Promise<store.DBInfo>;

export function Open(arg1:string):Promise<void>;

export function Query(arg1:string,arg2:Array<any>):Promise<store.QueryResult>;

export function Startup(arg1:context.Context):Promise<void>;
