// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['store']['Service']['Close']();
}

export function Exec(arg1, arg2) {
  return window['go']['store']['Service']['Exec'](arg1, arg2);
}

export function ExecBatch(arg1) {
  return window['go']['store']['Service']['ExecBatch'](arg1);
}

export function Info() {
  return window['go']['store']['Service']['Info']();
}

export function Open(arg1) {
  return window['go']['store']['Service']['Open'](arg1);
}

export function Query(arg1, arg2) {
  return window['go']['store']['Service']['Query'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['store']['Service']['Startup'](arg1);
}
